import json
import os
import errno

from utils.config_utils import parse_config

from enums import WriteStatus

"""a module with some editor/deleting/creating utils"""

config = parse_config()

def writefile(text: str, file: str) -> WriteStatus:
    """write file and return succes if it was writen or text of error if it wasn't"""
    try:
        with open(file, "w", encoding="utf-8") as f:
            f.write(text)
    except PermissionError:
        return WriteStatus.WRITE_NOT_PERMITTED
    except IsADirectoryError:
        return WriteStatus.IS_DIRERCTORY
    except OSError as err:
        if err.errno == errno.ENOSPC:
            return WriteStatus.NOT_ENOUGH_PLACE
        else:
            return WriteStatus.OS_FAILED
    except Exception:
        return WriteStatus.FAILED
        raise
    else:
        return WriteStatus.SUCCESS

def createwiki(name: str, description: str) -> WriteStatus:
    """not write text but create wiki barebone"""
    header_template = {
            "wikiname": f"{name}",
            "wikidescription": f"{description}",
            "enterpoint": "index.md"
}
    try:
        os.mkdir(f"{config["wikistorage"]}/{name}")
        with open(f"{config["wikistorage"]}/{name}/Header.json", "w", encoding="utf-8") as f:
            f.write(json.dumps(header_template))
        with open(f"{config["wikistorage"]}/{name}/index.md", "w", encoding="utf-8") as f:
            f.write("# Hello, this file is enterpoint by default and generated by microwiki, you can delete this text if you want to")
    except Exception:
        return WriteStatus.FAILED
        raise
    else:
        return WriteStatus.SUCCESS
