import json
import os

from utils.config_utils import parse_config

"""a module with some editor/deleting/creating utils"""

config = parse_config()

def writefile(text: str, file: str) -> str:
    """write file and return succes if it was writen or text of error if it wasn't"""
    try:
        with open(file, "w", encoding="utf-8") as f:
            f.write(text)
    except Exception as err:
        return f"error: {err}"
        raise
    else:
        return "succes"

def createwiki(name: str, description: str) -> str:
    """not write text but create wiki barebone"""
    header_template = {
            "wikiname": f"{name}",
            "wikidescription": f"{description}",
            "enterpoint": "index.md"
}
    try:
        os.mkdir(f"{config["wikistorage"]}/{name}")
        with open(f"{config["wikistorage"]}/{name}/Header.json", "w", encoding="utf-8") as f:
            f.write(json.dumps(header_template))
        with open(f"{config["wikistorage"]}/{name}/index.md", "w", encoding="utf-8") as f:
            f.write("# Hello, this file is enterpoint by default and generated by microwiki, you can delete this text if you want to")
    except Exception as err:
        return f"error: {err}"
        raise
    else:
        return "succes"
